### ISSUE TITLE
Add options for non-TLS transmission

### ISSUE THREAD

**Issue by puddingfactory** [puddingfactory/logentrus#1]
```go
const (
	host = "data.logentries.com"
	port = 443
)
```

I glanced over [the documentation around the different ports](https://docs.logentries.com/docs/input-token), etc., and this endpoint with port of 443 seemed to be the way to go if you wanted to use TLS.

I can't imagine why anyone would want to send in an insecure fashion (except for speed maybe?), but maybe there are other benefits that I'm not seeing right now.

If you want this changed... to be added as params for the New function call, for example... just reply and let me know or submit a pull request and I'll be happy to check it out.

**Comment by taitai42** [comment]
actually, i wrote my own logentries hook, and we connect as udp and on an unsecure channel, because we use these logs only for metrics and there is no reasons at all those logs should  slow our apps.

so speed over security can be good sometimes i guess

**Comment by puddingfactory** [comment]
Ah, great point! Seems like an excellent example of something that wouldn't need any security. I'll look into adding it in the coming week.

Thanks for your input :)

**Comment by puddingfactory** [comment]
Sorry, I a delay on getting to this; working through a write issue that seems related to timeouts: #2
