### ISSUE TITLE
Lower-case upper-case troubles again

### ISSUE THREAD

**Issue by dlebech** [puddingfactory/logentrus#4]
It seems that the logrus authors now decided that there's no turning back from the lower-case naming. From the top of the [README](https://github.com/sirupsen/logrus/blob/85b1699d505667d13f8ac4478c1debbf85d6c5de/README.md)

> Regretfully, there's no turning back now. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

I know this library was already changed once to lowercase and then changed back again to uppercase. Now it might seem it needs to be changed to lowercase permanently. What a mess :grimacing: 

I have been dealing with this issue with vendoring so far, but as more libraries start using lower-case referencing, it becomes difficult to avoid changing over.

What do you think?

**Comment by puddingfactory** [comment]
Great, thank you for catching this and sorry for the delay in responding! Given the quoted portion of the README you provided, I completely agree that this needs to be changed. Taking a look at your PR and expect to be approving it today
